### ISSUE TITLE
Incorrect Display Mode for Grouped Items in Side Navigation (Flex Instead of Block)"

### ISSUE THREAD

**Issue by CynthiaKamau** [openmrs/openmrs-esm-home#170]
https://github.com/openmrs/openmrs-esm-home/blame/4e16be566592d55c0d58353367f72e7fceb305f6/packages/esm-home-app/src/dashboard/home-dashboard.scss#L13

@denniskigen @vasharma05  what was the reason for adding this line ? For people using grouped links, it results in displaying the child links side by side as opposed to in a block format

<img width="324" alt="Screenshot 2024-01-08 at 21 05 48" src="https://github.com/openmrs/openmrs-esm-home/assets/19533785/32835d58-680f-4368-8389-6f5b1818979d">

**Comment by denniskigen** [comment]
Hey, @CynthiaKamau. iirc, this change was made [here](https://github.com/openmrs/openmrs-esm-home/commit/e683439f23d2a14be6e4d1477938c82a95452e6c) with the intention that it would be removed once https://github.com/openmrs/openmrs-esm-home/commit/5bf80e1107f9645ec05e16ac8d863cd81f985cd1 got merged. Is that right, @donaldkibet?

**Comment by CynthiaKamau** [comment]
> Hey, @CynthiaKamau. iirc, this change was made [here](https://github.com/openmrs/openmrs-esm-home/commit/e683439f23d2a14be6e4d1477938c82a95452e6c) with the intention that it would be removed once [5bf80e1](https://github.com/openmrs/openmrs-esm-home/commit/5bf80e1107f9645ec05e16ac8d863cd81f985cd1) got merged. Is that right, @donaldkibet? In local testing, have you found that the left nav links get rendered correctly when these styles get removed? Just the regular links first, before we move on to the grouped links. That could be a good place to start.

Yes, the normal links get rendered as expected when i remove the code snippet

**Comment by denniskigen** [comment]
Ok. Please go ahead and file a PR.

**Comment by CynthiaKamau** [comment]
> Ok. Please go ahead and file a PR.

Already did : https://github.com/openmrs/openmrs-esm-home/pull/171
